import { createHash, timingSafeEqual } from "node:crypto";

/**
 * Smartlead webhook → normalized provider event (input of outreach_apply_provider_event).
 *
 * Auth: a secret token in the webhook URL (?token=…), compared in constant time. The secret is generated by us and
 * stored only as the OUTREACH_WEBHOOK_SECRET environment variable. Idempotency: X-Request-Id (Smartlead's delivery id)
 * when present, otherwise a SHA-256 of the raw body — retries of the same delivery are applied exactly once.
 *
 * Smartlead's payloads differ between API versions (event_type vs event, EMAIL_REPLY vs EMAIL_REPLIED, flat fields vs
 * nested lead/reply objects), so parsing is deliberately tolerant. The lead is always resolved in the database by
 * (campaign id, lead email) — never trusted from free text.
 */
export const MIN_WEBHOOK_SECRET_LENGTH = 24;

export function isWebhookAuthorized(token: string | null | undefined, secret: string | null | undefined): boolean {
  if (!secret || secret.length < MIN_WEBHOOK_SECRET_LENGTH || !token) return false;
  const a = Buffer.from(token);
  const b = Buffer.from(secret);
  return a.length === b.length && timingSafeEqual(a, b);
}

export type ProviderEventType = "SENT" | "REPLY" | "BOUNCE" | "UNSUBSCRIBE" | "OPEN" | "CLICK" | "OTHER";

export interface ProviderEvent {
  id: string;
  provider: "smartlead";
  type: ProviderEventType;
  raw_type: string;
  campaign_id: string | null;
  lead_email: string | null;
  lead_id: string | null;
  sequence_number: number | null;
  message_id: string | null;
  stats_id: string | null;
  occurred_at: string | null;
  subject: string | null;
  body: string | null;
  from_email: string | null;
  to_email: string | null;
  payload: unknown;
}

const TYPE_MAP: Record<string, ProviderEventType> = {
  EMAIL_SENT: "SENT", FIRST_EMAIL_SENT: "SENT",
  EMAIL_REPLY: "REPLY", EMAIL_REPLIED: "REPLY", UNTRACKED_REPLIES: "REPLY",
  EMAIL_BOUNCE: "BOUNCE", EMAIL_BOUNCED: "BOUNCE",
  LEAD_UNSUBSCRIBED: "UNSUBSCRIBE", EMAIL_UNSUBSCRIBED: "UNSUBSCRIBE",
  EMAIL_OPEN: "OPEN", EMAIL_OPENED: "OPEN",
  EMAIL_LINK_CLICK: "CLICK", EMAIL_CLICKED: "CLICK",
};

type Json = Record<string, unknown>;
const obj = (v: unknown): Json => (v && typeof v === "object" && !Array.isArray(v) ? (v as Json) : {});
const str = (...vs: unknown[]): string | null => {
  for (const v of vs) if (v !== null && v !== undefined && String(v).trim() !== "") return String(v).trim();
  return null;
};
const email = (v: string | null) => {
  const m = v?.match(/[^\s<>"]+@[^\s<>"]+\.[^\s<>"]+/);
  return m ? m[0].toLowerCase() : null;
};

/** HTML → readable text (inbound replies are stored as text; never rendered as HTML). */
export function htmlToText(html: string | null): string | null {
  if (!html) return null;
  if (!/<[a-z!/]/i.test(html)) return html.trim();
  return html
    .replace(/<(script|style)[\s\S]*?<\/\1>/gi, " ")
    .replace(/<br\s*\/?>/gi, "\n").replace(/<\/(p|div|li|tr|h\d|blockquote)>/gi, "\n")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'")
    .replace(/[ \t]+\n/g, "\n").replace(/\n{3,}/g, "\n\n").trim();
}

/** Strips quoted history ("Op … schreef …:", "On … wrote:", "> …") so classification sees only the new text. */
export function stripQuoted(text: string | null): string | null {
  if (!text) return text;
  const lines = text.split("\n");
  const out: string[] = [];
  for (const line of lines) {
    if (/^\s*(op .{3,120} (schreef|heeft .* geschreven)|on .{3,160} wrote:?|-{2,}\s*original message|-{2,}\s*oorspronkelijk bericht|from:\s.*@|van:\s.*@)/i.test(line)) break;
    if (/^\s*>/.test(line)) continue;
    out.push(line);
  }
  return out.join("\n").trim() || text.trim();
}

/** Payload subset kept for audit (no message bodies twice, nothing beyond what the provider sent). */
function auditPayload(p: Json): Json {
  const keep = ["event_type", "event", "campaign_id", "campaign_name", "sequence_number", "time_sent", "time_replied", "message_id", "stats_id", "lead_id", "sl_email_lead_id", "event_timestamp", "timestamp"];
  return Object.fromEntries(Object.entries(p).filter(([k]) => keep.includes(k)));
}

export function normalizeSmartleadEvent(payload: unknown, opts: { requestId?: string | null; rawBody: string }): ProviderEvent | null {
  const p = obj(payload);
  const rawType = str(p.event_type, p.event, p.type)?.toUpperCase() ?? null;
  if (!rawType) return null;
  const type = TYPE_MAP[rawType] ?? "OTHER";
  const lead = obj(p.lead ?? p.lead_data);
  const reply = obj(p.reply ?? p.reply_message);
  const sent = obj(p.sent_message);
  const from = email(str(p.from_email, reply.from, p.from));
  const to = email(str(p.to_email, p.to, sent.to));
  // Lead address: explicit fields first; for replies the lead is the sender, for sends the recipient.
  const leadEmail = email(str(p.lead_email, p.sl_lead_email, lead.email)) ?? (type === "REPLY" ? from : to);
  const body = type === "REPLY" ? stripQuoted(htmlToText(str(p.reply_body, reply.text, reply.html, reply.body, p.preview_text))) : type === "SENT" ? htmlToText(str(p.custom_email_message, sent.html, sent.text)) : null;
  const id = str(opts.requestId) ? `sl:req:${opts.requestId}` : `sl:sha:${createHash("sha256").update(opts.rawBody).digest("hex")}`;
  const seq = Number(str(p.sequence_number, p.seq_number, sent.sequence_number));
  return {
    id,
    provider: "smartlead",
    type,
    raw_type: rawType,
    campaign_id: str(p.campaign_id, p.email_campaign_id, obj(p.campaign).id),
    lead_email: leadEmail,
    lead_id: str(p.lead_id, p.sl_email_lead_id, lead.id),
    sequence_number: Number.isFinite(seq) && seq > 0 ? seq : null,
    message_id: str(type === "REPLY" ? (reply.message_id ?? p.reply_message_id ?? p.message_id) : (sent.message_id ?? p.message_id)),
    stats_id: str(p.stats_id, p.email_stats_id),
    occurred_at: toIso(str(type === "REPLY" ? (p.time_replied ?? reply.time) : (p.time_sent ?? sent.time), p.event_timestamp, p.timestamp)),
    subject: str(p.subject, p.custom_subject, reply.subject, sent.subject),
    body: body ? body.slice(0, 20_000) : null,
    from_email: from,
    to_email: to,
    payload: auditPayload(p),
  };
}

function toIso(v: string | null): string | null {
  if (!v) return null;
  const t = Date.parse(v);
  return Number.isFinite(t) ? new Date(t).toISOString() : null;
}
